document.writeln("    <div class=\"span3 left-bars\" style=\"float:left; z-index:100;\">");
document.writeln("    <div class=\"leftbar\">");
document.writeln("    <div class=\"leftbar1\" >");
document.writeln("    <div class=\"senvenbaby-logo\"><img src=\"img/news_20.png\" width=\"170\" height=\"190\" alt=\"\"></div>");
document.writeln("    ");
document.writeln("    <div class=\"leftnav\">");
document.writeln("    <ul>");
document.writeln("    <li><a href=\"index.html\"  onclick=\"change_bg(this)\" class=\"select\">首页</a></li>");
document.writeln("    <li><a href=\"http://item.taobao.com/item.htm?spm=686.1000925.1000774.67.fHX4Pf&id=39847891582\" target=\"_blank\"  onclick=\"change_bg(this)\">产品</a></li>"); 
document.writeln("    <li><a href=\"app.html\"  onclick=\"change_bg(this)\">移动应用</a></li>");
document.writeln("    <li><a href=\"download.html\"  onclick=\"change_bg(this)\">下载</a></li>");
document.writeln("    <li><a href=\"about.html\" onclick=\"change_bg(this)\">关于</a></li>");
document.writeln("    </ul>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("    <div class=\"copyright-bar\">");
document.writeln("      <div class=\"copyright\">copyright © 2014 SEVENBABY.<br>All Rights Reserved.<br><br></div> ");
document.writeln("   </div>");
document.writeln("  </div>");
document.writeln("  </div>");
document.writeln("    </div>");